language: ruby
rvm:
  - "2.0"
before_script:
  - psql -c 'create database ogre_test;' -U postgres
  - bundle exec rake db:migrate db:test:load
notifications:
  email:
    on_success: change
    on_failure: always
